server:
  port: 7090
  
zeebe:
  client:
    broker:
      contactPoint: "10.98.22.166:26500"
    security:
      plaintext: true
    worker:
      defaultName: multijobprocess-worker
      
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8061/eureka      
 